# Generated by Django 3.2 on 2021-04-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('ticket', models.TextField(max_length=250, verbose_name='Ticket')),
            ],
        ),
    ]
